server:
  port:
    8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: root
    password: 5133

  # JPA 설정
  jpa:
    generatep-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

# log 를 debug 모드로 출력하는 방법 (println 대신 이걸 사용하는 것이 좋다)
logging:
  level:
    com:
      min:
        springdata: debug
